"""add group settings

Revision ID: 23e8e0fd5ce2
Revises: 6f0fc8f24c53
Create Date: 2025-04-06 02:12:50.922793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e8e0fd5ce2'
down_revision: Union[str, None] = '6f0fc8f24c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('responds_to_text', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('groups', sa.Column('responds_to_voice', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('groups', 'responds_to_voice')
    op.drop_column('groups', 'responds_to_text')
    # ### end Alembic commands ###
