"""add responds_to_photo field to groups

Revision ID: 2419e308fb27
Revises: 360332c9dcf3
Create Date: 2025-04-22 17:07:10.326761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2419e308fb27'
down_revision: Union[str, None] = '360332c9dcf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('responds_to_photo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'responds_to_photo')
    # ### end Alembic commands ###
