"""Add file_path and mime_type to stickers table

Revision ID: 5474cb045f8b
Revises: 0173f8daad34
Create Date: 2025-05-08 19:12:53.302438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5474cb045f8b'
down_revision: Union[str, None] = '0173f8daad34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the new columns without dropping existing indexes or columns
    op.add_column('stickers', sa.Column('file_path', sa.String(length=512), nullable=True))
    op.add_column('stickers', sa.Column('mime_type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the columns we added
    op.drop_column('stickers', 'mime_type')
    op.drop_column('stickers', 'file_path')
    # ### end Alembic commands ###
