"""Add group responds_to_video_note and transcribe fields

Revision ID: 588db9643901
Revises: add_transcribe_video_note
Create Date: 2025-04-29 15:48:18.849441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588db9643901'
down_revision: Union[str, None] = 'add_transcribe_video_note'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('responds_to_video_note', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('groups', sa.Column('transcribe_voice_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('groups', sa.Column('transcribe_video_note', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'transcribe_video_note')
    op.drop_column('groups', 'transcribe_voice_only')
    op.drop_column('groups', 'responds_to_video_note')
    # ### end Alembic commands ###
