"""add_telegram_message_id

Revision ID: 5bb3801918cd
Revises: 23e8e0fd5ce2
Create Date: 2025-04-20 00:13:50.161851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb3801918cd'
down_revision: Union[str, None] = '23e8e0fd5ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('telegram_message_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_message_history_telegram_message_id'), 'message_history', ['telegram_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_history_telegram_message_id'), table_name='message_history')
    op.drop_column('message_history', 'telegram_message_id')
    # ### end Alembic commands ###
