"""Add user settings columns (role remains String)

Revision ID: 68a85f7d45f5
Revises: a682d1af0563
Create Date: 2025-04-01 02:35:52.443314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a85f7d45f5'
down_revision: Union[str, None] = 'a682d1af0563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_history_user_id'), 'message_history', ['user_id'], unique=False)
    op.drop_constraint('message_history_user_id_fkey', 'message_history', type_='foreignkey')
    op.create_foreign_key(None, 'message_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('responds_to_text', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('responds_to_voice', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('transcribe_voice_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'transcribe_voice_only')
    op.drop_column('users', 'responds_to_voice')
    op.drop_column('users', 'responds_to_text')
    op.drop_constraint(None, 'message_history', type_='foreignkey')
    op.create_foreign_key('message_history_user_id_fkey', 'message_history', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_message_history_user_id'), table_name='message_history')
    # ### end Alembic commands ###
