"""Add is_global_disabled to group

Revision ID: cdebc0646660
Revises: 588db9643901
Create Date: 2025-04-29 15:49:49.838528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdebc0646660'
down_revision: Union[str, None] = '588db9643901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('is_global_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'is_global_disabled')
    # ### end Alembic commands ###
