"""remove file_extension column

Revision ID: remove_file_extension
Revises: add_file_extension
Create Date: 2024-03-21 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'remove_file_extension'
down_revision: Union[str, None] = 'add_file_extension'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_history', 'file_extension')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('file_extension', sa.String(length=10), nullable=True))
    # ### end Alembic commands ### 